# Global costmap parameters
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true

# Local costmap parameters
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false

# Trajectory planner parameters
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_y: 0.5
  min_vel_y: -0.5
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

